# Generated by Django 6.0.4 on 2026-04-15 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата активации')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='active_clients', to='contracts.contract', verbose_name='Контракт')),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer', to='leads.lead', verbose_name='Потенциальный клиент')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
