# Generated by Django 6.0.4 on 2026-04-14 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('channel', models.CharField(choices=[('vk', 'ВКонтакте'), ('ig', 'Instagram'), ('tg', 'Telegram'), ('yandex', 'Яндекс.Директ'), ('google', 'Google Ads'), ('other', 'Другое')], max_length=20, verbose_name='Канал продвижения')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет>')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='services.service', verbose_name='Рекламируемая услуга')),
            ],
            options={
                'verbose_name': 'Рекламная компания',
                'verbose_name_plural': 'Рекламные компании',
            },
        ),
    ]
