# Generated by Django 6.0.4 on 2026-04-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет'),
        ),
    ]
